package JFrame;

import Model.DAO.CreatePractica;
import Model.DTO.CentroPractica;
import Model.DTO.Practica;
import Model.DTO.Usuario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lissette
 */
public class CoordinadorCrearActa1 extends javax.swing.JFrame {
    private String emailAlumno;
    private int idpracticaalumno;
    /**
     * Creates new form CoordinadorCrearActa1
     */
    public CoordinadorCrearActa1() {
        initComponents();
        llenarComboDocentes();
        llenarComboCentros();
        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        cmb_centros.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txtNomCentro1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNomAlum = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtuserNameCentro = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lblMsje = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtDv = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmb_tipo_practica = new javax.swing.JComboBox<>();
        cmb_nom_docente1 = new javax.swing.JComboBox();
        cmb_centros = new javax.swing.JComboBox();
        check_1 = new javax.swing.JCheckBox();
        btn_volver = new javax.swing.JButton();
        txtDiaI = new javax.swing.JTextField();
        txtMesI = new javax.swing.JTextField();
        txtAnioI = new javax.swing.JTextField();
        txtDiaT = new javax.swing.JTextField();
        txtMesT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_cal_fch = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNomCentro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtf_email_centro = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txtAnioT = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jRadioButton1.setText("jRadioButton1");

        txtNomCentro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomCentro1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre alumno");

        jLabel2.setText("Rut alumno");

        jLabel3.setText("Carrera");

        jLabel4.setText("Fecha inicio");

        jLabel5.setText("Fecha termino");

        jLabel6.setText("Nombre del centro de práctica");

        jLabel12.setText("jLabel12");

        jLabel14.setText("Nombre profesor guía");

        txtNomAlum.setEditable(false);
        txtNomAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomAlumActionPerformed(evt);
            }
        });
        txtNomAlum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomAlumKeyTyped(evt);
            }
        });

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        txtuserNameCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserNameCentroActionPerformed(evt);
            }
        });

        txtCarrera.setEditable(false);
        txtCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarreraActionPerformed(evt);
            }
        });
        txtCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarreraKeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel17.setText("-");

        jLabel20.setText("Apellido paterno");

        jLabel21.setText("Apellido materno");

        txtApellido1.setEditable(false);
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });
        txtApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido1KeyTyped(evt);
            }
        });

        txtApellido2.setEditable(false);
        txtApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido2ActionPerformed(evt);
            }
        });
        txtApellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido2KeyTyped(evt);
            }
        });

        txtDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDvActionPerformed(evt);
            }
        });
        txtDv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDvKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Práctica");

        cmb_tipo_practica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesional", "Laboral" }));
        cmb_tipo_practica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipo_practicaActionPerformed(evt);
            }
        });

        check_1.setText("Existente");
        check_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_1ActionPerformed(evt);
            }
        });

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        txtDiaI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaIKeyTyped(evt);
            }
        });

        txtMesI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesIKeyTyped(evt);
            }
        });

        txtAnioI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioIKeyTyped(evt);
            }
        });

        txtDiaT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaTKeyTyped(evt);
            }
        });

        txtMesT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesTKeyTyped(evt);
            }
        });

        jLabel8.setText("/");

        jLabel9.setText("/");

        jLabel10.setText("/");

        jLabel11.setText("/");

        btn_cal_fch.setText("Calcular");
        btn_cal_fch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cal_fchActionPerformed(evt);
            }
        });

        jLabel13.setText("* Fecha estimada, calculada en base a 9 horas de trabajo diarias.");

        txtNomCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomCentroActionPerformed(evt);
            }
        });

        jLabel15.setText("Nombre Centro:");

        jLabel16.setText("UserName:");

        jLabel18.setText("Email:");

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jMenu3.setText("Home");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Crear");

        jMenuItem2.setText("Alumno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Acta 1");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Reportes");

        jMenuItem4.setText("General");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText("Específico");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Ver");

        jMenuItem6.setText("Asignaciones");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenuItem7.setText("Centros de prácticas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuItem1.setText("Detalle prácticas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuBar1.add(jMenu8);

        jMenu6.setText("Cerrar Sesión");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtDiaT, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                            .addComponent(txtDiaI))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMesI, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                            .addComponent(txtMesT))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)
                                                .addComponent(txtAnioI, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAnioT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cal_fch))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_tipo_practica, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(90, 90, 90)
                                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(check_1)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmb_centros, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(txtuserNameCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(jtf_email_centro)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_nom_docente1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(29, 29, 29)
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(94, 94, 94))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMsje)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnBuscar)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_editar)
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_volver, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btn_eliminar)
                                                .addGap(94, 94, 94)))))))
                        .addGap(0, 41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMsje)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmb_tipo_practica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnioI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cal_fch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtDiaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMesT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(txtAnioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jLabel13)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(check_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_centros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuserNameCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtf_email_centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_nom_docente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_volver)
                        .addComponent(btn_eliminar)
                        .addComponent(btn_editar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomAlumActionPerformed

    }//GEN-LAST:event_txtNomAlumActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Validar();
        lblMsje.setText(" ");
        String fechaI = txtDiaI.getText() + "/" + txtMesI.getText() + "/" + txtAnioI.getText();
        String fechaT = txtDiaT.getText() + "/" + txtMesT.getText() + "/" + txtAnioT.getText();
        try {
            Usuario docente = (Usuario) cmb_nom_docente1.getSelectedItem();
            CentroPractica centro = (CentroPractica) cmb_centros.getSelectedItem();
            Practica practica = new Practica();
            int cantidad_horas = 0;
            int idcentro = 0;
            String nombreCentro = "";
            //Obtenemos atributos del formulario
            int rut_alumno = Integer.parseInt(txtRut.getText());
            
            
            String username ="";
            String pass = "";
            //randon para pass centro practica
            int numero = (int) (Math.random() * 100) + 1;
            //Verificamos si es un centro nuevo
            if (check_1.isSelected()) {
                //Existe el centro traemos su ID
                idcentro = centro.getIdCentroPractica();
                nombreCentro = centro.getNombreCentro();
            } else {
                nombreCentro = txtuserNameCentro.getText();
                username = txtuserNameCentro.getText();
                pass = txtuserNameCentro.getText()+""+numero;
            }
            
            //Calculamos cantidad de horas según tipo
            if (cmb_tipo_practica.getSelectedItem().toString().equals("Profesional")) {
                cantidad_horas = 600;
            } else {
                cantidad_horas = 480;

            }
            String email_centro = jtf_email_centro.getText();

            if (practica.Create(rut_alumno, docente.getRut(), fechaI, fechaT, cmb_tipo_practica.getSelectedItem().toString(), cantidad_horas, idcentro, nombreCentro,username,pass,email_centro)) {
                JOptionPane.showMessageDialog(null, "Acta1 ha sido creada", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                //Mandamos un email al Alumno con detalles:
                Usuario alumno = new Usuario();
                alumno.mandarEmail(emailAlumno, "Se acaba de asignar su nueva practica, favor revisar detalles en la web", "Práctica asignada");
                //Mandamos email al Profesor
                docente.mandarEmail(docente.getEmail(), "Se acaba de asignar un nuevo alumno en práctica, favor revisar portal web para más detalles", "Nueva asignación de Alumno DUOC UC");
                //Mandamo email al centro
                if (!check_1.isSelected()) {
                //Si esta seleccionado es verdadero ( existe ) por lo tanto no debería entrar
                Usuario centro_pract = new Usuario();
                centro_pract.mandarEmail(email_centro, "Sus datos de acceso son: USERNAME: "+username+" y su passwors es: "+pass, "Datos de acceso portal DUOC UC");
                } 
                
                
                llenarComboCentros();
                
            } else {
                JOptionPane.showMessageDialog(null, null, "Practica no pudo ser creada", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, null, "Practica no pudo ser creada" + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        lblMsje.setText("");
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        lblMsje.setText("");
        btnGuardar.setEnabled(true);
        btn_editar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        try {
            Usuario user = new Usuario();
            user.setRut(Integer.parseInt(txtRut.getText()));
            user.setDv(txtDv.getText());
            if (user.Buscar(4)) {

                txtNomAlum.setText(user.getNombres());
                txtApellido1.setText(user.getApellido1());
                txtApellido2.setText(user.getApellido2());
                txtCarrera.setText(user.nombre_carrera());
                emailAlumno = user.getEmail();
                idpracticaalumno = user.getId_practica();
                
                //Damos mensaje si es que el alumno ya tiene una práctica
                if(user.tienePractica(user.getRut())){
                    JOptionPane.showMessageDialog(this,"Alumno ya posee una práctica");
                    System.out.println("id_practica = "+user.getId_practica());
                    btnGuardar.setEnabled(false);
                    btn_editar.setEnabled(true);
                    btn_eliminar.setEnabled(true);
                    check_1.setSelected(true);//Se selecciona que existe
                    cmb_centros.setEnabled(true);//Habilitamos combobox
                    txtNomCentro.setEnabled(false);
                    txtuserNameCentro.setEnabled(false);
                    jtf_email_centro.setEnabled(false);
                    
                    //Usamos el Procedimiento almacenado en la clase Practica
                    Practica prac = new Practica();
                    prac.DatosPractica(user.getRut());
                    
                    CentroPractica cen = new CentroPractica();
                    
                    cen.setIdCentroPractica(prac.getIdCentroPractica());
                    cmb_centros.setSelectedItem(cen);
                    cmb_tipo_practica.setSelectedItem(prac.getTipoHorasPractica());
                    
                    Usuario u = new Usuario();
                    u.setRut(prac.getRutDocente());
                    cmb_nom_docente1.setSelectedItem(u);
                    
                    System.out.println("Fecha Inicio: "+prac.getFechaInicio());
                    System.out.println("Fecha Termino: "+prac.getFechaTerimno());
                    
                    //Llenamos los txt de las fechas
                    String[] fechaIni = prac.getFechaInicio().split("-");
                    String[] fechaTer = prac.getFechaTerimno().split("-");
                    
                    txtDiaI.setText(fechaIni[2]);
                    txtMesI.setText(fechaIni[1]);
                    txtAnioI.setText(fechaIni[0]);
                    
                    txtDiaT.setText(fechaTer[2]);
                    txtMesT.setText(fechaTer[1]);
                    txtAnioT.setText(fechaTer[0]);
                    
                }
                

            } else {
                JOptionPane.showMessageDialog(this,"El alumno no ha sido encontrado");
                //limpiar campos
                limpiarFormulario();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, null, "Ocurrio un error" + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void check_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_1ActionPerformed
        if (check_1.isSelected()) {
            cmb_centros.setEnabled(true);
            txtuserNameCentro.setEnabled(false);
            txtNomCentro.setEnabled(false);
        } else {
            cmb_centros.setEnabled(false);
            txtuserNameCentro.setEnabled(true);
            txtNomCentro.setEnabled(true);
        }
    }//GEN-LAST:event_check_1ActionPerformed

    private void txtNomAlumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomAlumKeyTyped

    }//GEN-LAST:event_txtNomAlumKeyTyped

    private void txtApellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1KeyTyped

    }//GEN-LAST:event_txtApellido1KeyTyped

    private void txtApellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido2KeyTyped

    }//GEN-LAST:event_txtApellido2KeyTyped

    private void txtCarreraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarreraKeyTyped

    }//GEN-LAST:event_txtCarreraKeyTyped

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed

    }//GEN-LAST:event_txtRutActionPerformed

    private void txtDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDvActionPerformed

    }//GEN-LAST:event_txtDvActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed

    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido2ActionPerformed

    }//GEN-LAST:event_txtApellido2ActionPerformed

    private void txtCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarreraActionPerformed

    }//GEN-LAST:event_txtCarreraActionPerformed

    private void txtuserNameCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserNameCentroActionPerformed

    }//GEN-LAST:event_txtuserNameCentroActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        IndexCoordinadorCarrera frame = new IndexCoordinadorCarrera();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        char c = evt.getKeyChar();
        int largo = 8;
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (txtRut.getText().length() >= largo) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo 8 caracteres");
        }
    }//GEN-LAST:event_txtRutKeyTyped

    private void txtDvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDvKeyTyped
        //int largo = 1;
        //if (txtRut.getText().length() >= largo) {
        //    evt.consume();
        //    JOptionPane.showMessageDialog(this, "Ingrese solo un caracter");
        //}
        
    }//GEN-LAST:event_txtDvKeyTyped

    private void txtDiaIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaIKeyTyped
        char c = evt.getKeyChar();
        int largo = 2;
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (txtDiaI.getText().length() >= largo) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo 2 caracteres");
        }
    }//GEN-LAST:event_txtDiaIKeyTyped

    private void txtMesIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesIKeyTyped
        char c = evt.getKeyChar();
        int largo = 2;
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (txtMesI.getText().length() >= largo) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo 2 caracteres");
        }
    }//GEN-LAST:event_txtMesIKeyTyped

    private void txtAnioIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioIKeyTyped
        char c = evt.getKeyChar();
        int largo = 4;
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (txtAnioI.getText().length() >= largo) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo 4 caracteres");
        }
    }//GEN-LAST:event_txtAnioIKeyTyped

    private void txtDiaTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaTKeyTyped
        char c = evt.getKeyChar();
        int largo = 2;
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (txtDiaT.getText().length() >= largo) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo 2 caracteres");
        }
    }//GEN-LAST:event_txtDiaTKeyTyped

    private void txtMesTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesTKeyTyped
        char c = evt.getKeyChar();
        int largo = 2;
        if (c < '0' || c > '9') {
            evt.consume();
        }
        if (txtMesT.getText().length() >= largo) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo 2 caracteres");
        }
    }//GEN-LAST:event_txtMesTKeyTyped

    private void btn_cal_fchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cal_fchActionPerformed
        int tipo = cmb_tipo_practica.getSelectedIndex();
        int num_horas = (tipo==0)?360:240;
        Calendar calendar = Calendar.getInstance();
        calendar.set(Integer.parseInt(txtAnioI.getText()), Integer.parseInt(txtMesI.getText()), Integer.parseInt(txtDiaI.getText()));
        //calculos de días cada día se trabaj 9 horas.
        int dias = num_horas / 9;
        
        calendar.add(Calendar.DAY_OF_YEAR, dias);
               
        SimpleDateFormat dateFormaty = new SimpleDateFormat("yyyy");
        //Integer.parseInt(dateFormat.format(calendar.getTime()));
        SimpleDateFormat dateFormatm = new SimpleDateFormat("MM");
        SimpleDateFormat dateFormatd = new SimpleDateFormat("dd");
        
        txtAnioT.setText(dateFormaty.format(calendar.getTime()));
        txtMesT.setText(dateFormatm.format(calendar.getTime()));
        txtDiaT.setText(dateFormatd.format(calendar.getTime()));
        
        System.out.println("fecha: "+calendar.getTime());
    }//GEN-LAST:event_btn_cal_fchActionPerformed

    private void txtNomCentro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomCentro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomCentro1ActionPerformed

    private void txtNomCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomCentroActionPerformed

    private void cmb_tipo_practicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipo_practicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipo_practicaActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        Validar();
        
        String fechaInicio = txtDiaI.getText() + "/" + txtMesI.getText() + "/" + txtAnioI.getText();
        String fechaTermino = txtDiaT.getText() + "/" + txtMesT.getText() + "/" + txtAnioT.getText();
        try {
            Usuario docente = (Usuario) cmb_nom_docente1.getSelectedItem();
            CentroPractica centro = (CentroPractica) cmb_centros.getSelectedItem();
            Usuario alumno = new Usuario();
            int rut_alumno = Integer.parseInt(txtRut.getText());
            alumno.tienePractica(rut_alumno);
            Practica practica = new Practica();
            int cantidad_horas = 0;
            int idcentro = 0;
            String nombreCentro = "";
       
            //Obtenemos valores del Formulario

            String username ="";
            String pass = "";
            //randon para pass centro practica
            int numero = (int) (Math.random() * 100) + 1;
            //Verificamos si es un centro nuevo
            if (check_1.isSelected()) {
                //Existe el centro traemos su ID
                idcentro = centro.getIdCentroPractica();
                nombreCentro = centro.getNombreCentro();
            } else {
                nombreCentro = txtuserNameCentro.getText();
                username = txtuserNameCentro.getText();
                pass = txtuserNameCentro.getText()+""+numero;
            }
            
            //Calculamos cantidad de horas según tipo
            if (cmb_tipo_practica.getSelectedItem().toString().equals("Profesional")) {
                cantidad_horas = 600;
            } else {
                cantidad_horas = 480;

            }
            String email_centro = jtf_email_centro.getText();
            
            if(practica.Update(rut_alumno, docente.getRut(), fechaInicio, fechaTermino, cmb_tipo_practica.getSelectedItem().toString(), cantidad_horas, idcentro, nombreCentro, username, pass, email_centro, alumno.getId_practica())){
                JOptionPane.showMessageDialog(null, "Practica ha sido editada", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
                //Mandamos un email al Alumno con detalles:
                System.out.println("Este es el email: "+emailAlumno);
                alumno.mandarEmail(emailAlumno, "Se acaba de actualizar su practica, favor revisar detalles en la web", "Práctica asignada");
                //Mandamos email al Profesor
                //docente.mandarEmail(docente.getEmail(), "Se acaba de actualizar o agregar un nuevo alumno en práctica, favor revisar portal web para más detalles", "Nueva asignación de Alumno DUOC UC");
                //Mandamo email al centro
                //if (!check_1.isSelected()) {
                //Si esta seleccionado es verdadero ( existe ) por lo tanto no debería entrar
                //Usuario centro_pract = new Usuario();
                //centro_pract.mandarEmail(email_centro, "Sus datos de acceso son: USERNAME: "+username+" y su passwors es: "+pass, "Datos de acceso portal DUOC UC");
                //} 
 
            }else{
            
                JOptionPane.showMessageDialog(null, null, "Practica no pudo ser creada", JOptionPane.ERROR_MESSAGE);
            }
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, null, "Practica no pudo ser creada" + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        try {
            Practica prac = new Practica();
            if(prac.Delete(Integer.parseInt(txtRut.getText()), idpracticaalumno)){
                System.out.println("id practica: "+idpracticaalumno);
                System.out.println("rut alumno: "+txtRut.getText());
                JOptionPane.showMessageDialog(null, "Practica ha sido eliminada", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormulario();
            }else{
                JOptionPane.showMessageDialog(null, null, "No se pudo eliminar", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, null, "No se pudo eliminar" + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        IngresarAlumno frame = new IngresarAlumno();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CoordinadorCrearActa1 frame = new CoordinadorCrearActa1();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ReportesCoorinador frame = new ReportesCoorinador();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ReportesCoordinadorEspecifico frame = new ReportesCoordinadorEspecifico();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        AsignacionesDocentes frame = new AsignacionesDocentes();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CentrosPracticaGestion frame = new CentrosPracticaGestion();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DetallePracticaAlumnos frame = new DetallePracticaAlumnos();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoordinadorCrearActa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoordinadorCrearActa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoordinadorCrearActa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoordinadorCrearActa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoordinadorCrearActa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btn_cal_fch;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_volver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox check_1;
    private javax.swing.JComboBox cmb_centros;
    private javax.swing.JComboBox cmb_nom_docente1;
    private javax.swing.JComboBox<String> cmb_tipo_practica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jtf_email_centro;
    private javax.swing.JLabel lblMsje;
    private javax.swing.JTextField txtAnioI;
    private javax.swing.JTextField txtAnioT;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtDiaI;
    private javax.swing.JTextField txtDiaT;
    private javax.swing.JTextField txtDv;
    private javax.swing.JTextField txtMesI;
    private javax.swing.JTextField txtMesT;
    private javax.swing.JTextField txtNomAlum;
    private javax.swing.JTextField txtNomCentro;
    private javax.swing.JTextField txtNomCentro1;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtuserNameCentro;
    // End of variables declaration//GEN-END:variables
        private void limpiarFormulario() {
        txtRut.setText("");
        txtDv.setText("");
        txtNomAlum.setText("");
        txtApellido1.setText("");
        txtApellido2.setText("");
        txtCarrera.setText("");
        txtuserNameCentro.setText("");
        txtDiaI.setText("");
        txtMesI.setText("");
        txtAnioI.setText("");
        txtDiaT.setText("");
        txtMesT.setText("");
        txtAnioT.setText("");
        check_1.setSelected(false);//Se selecciona que existe
        cmb_centros.setEnabled(false);//Habilitamos combobox
        txtNomCentro.setEnabled(true);
        txtuserNameCentro.setEnabled(true);
        jtf_email_centro.setEnabled(true);
    }

    private void llenarComboDocentes() {
        Usuario user = new Usuario();
        ArrayList<Usuario> docentes = user.BuscarTipoUsuario(3);

        for (Usuario docente : docentes) {
            cmb_nom_docente1.addItem(docente);
        }
    }

    private void llenarComboCentros() {
        cmb_centros.removeAllItems();
        CentroPractica centro = new CentroPractica();
        ArrayList<CentroPractica> centros = centro.BuscarTodosCentros();
        for (CentroPractica centro1 : centros) {
            cmb_centros.addItem(centro1);
        }
    }

    private void Validar() {
        try {
            if (!txtApellido1.getText().isEmpty()) {
                if (!txtApellido2.getText().isEmpty()) {
                    if (!txtCarrera.getText().isEmpty()) {
                        if (!txtDv.getText().isEmpty()) {
                            if (!txtNomAlum.getText().isEmpty()) {
                                if (!txtRut.getText().isEmpty()) {
                                    if (Integer.parseInt(txtDiaI.getText()) >= 1 && Integer.parseInt(txtDiaI.getText()) <= 31) {
                                        if (Integer.parseInt(txtMesI.getText()) >= 1 && Integer.parseInt(txtMesI.getText()) <= 12) {
                                            if (Integer.parseInt(txtAnioI.getText()) <= 2017) {
                                                if (Integer.parseInt(txtDiaT.getText()) >= 1 && Integer.parseInt(txtDiaT.getText()) <= 31) {
                                                    if (Integer.parseInt(txtMesT.getText()) >= 1 && Integer.parseInt(txtMesT.getText()) <= 12) {
                                                        if (Integer.parseInt(txtAnioT.getText()) <= 2017) {

                                                            System.out.println("Validado");
                                                        } else {
                                                            JOptionPane.showMessageDialog(this, "El año debe ser menor a 2017");
                                                        }
                                                    } else {
                                                        JOptionPane.showMessageDialog(this, "El mes debe estar entre 1 y 12");
                                                    }
                                                } else {
                                                    JOptionPane.showMessageDialog(this, "El dia debe estar entre 1 y 31");
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(this, "El año debe ser menor a 2017");
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(this, "El mes debe estar entre 1 y 12");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(this, "El dia debe estar entre 1 y 31");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Ingrese el rut", "Error!", JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Ingrese el nombre del alumno", "Error!", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Ingrese el dv", "Error!", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrese la carrera", "Error!", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ingrese el apellido materno", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese el apellido paterno", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    

}
