package JFrame;

import Model.DAO.EscuelaDAO;
import Model.DTO.Escuela;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Denisse
 */
public class EscuelaEliminar extends javax.swing.JFrame {

    /**
     * Creates new form EscuelaEliminar
     */
    public EscuelaEliminar() {
        initComponents();
        EscuelaDAO esc = new EscuelaDAO();
        actualizarComboBox(esc.BuscarTodasLasEscuelas());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        cmb_Nombre = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Eliminar Escuela");

        jLabel1.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnEliminar)
                        .addGap(49, 49, 49)
                        .addComponent(btn_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(80, 80, 80)
                                .addComponent(cmb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(115, 115, 115)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btn_volver))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String nombreEscuelaAEliminar = cmb_Nombre.getSelectedItem().toString();
        EscuelaDAO esc = new EscuelaDAO();
        Escuela escuela = esc.BuscarPorNombreDeEscuela(nombreEscuelaAEliminar);
        if (esc.Delete(nombreEscuelaAEliminar)){
            JOptionPane.showMessageDialog(null, "Escuela "+ nombreEscuelaAEliminar + " eliminada", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            actualizarComboBox(esc.BuscarTodasLasEscuelas());
        }
        else{
            JOptionPane.showMessageDialog(null, "Escuela "+ nombreEscuelaAEliminar + " no pudo ser eliminada", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
        
        actualizarComboBox(esc.BuscarTodasLasEscuelas());
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        this.setVisible(false);
        CoordinadorCrearEscuela coorCrearEscuela = new CoordinadorCrearEscuela();
        coorCrearEscuela.setVisible(true);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void actualizarComboBox(ArrayList<Escuela> escuelas){
        cmb_Nombre.removeAll();
        cmb_Nombre.removeAllItems();
        
        for(Escuela e : escuelas){
            cmb_Nombre.addItem(e.getNombreEscuela());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_Nombre;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
