package JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Camilo-PC
 */
public class IndexJefeCarrera extends javax.swing.JFrame {

    /**
     * Creates new form IndexJefeCarrera
     */
    public IndexJefeCarrera() {
        initComponents();
        jl_nombre_usuario.setText(Inicio.usuarioActual.getNombres()+" "+Inicio.usuarioActual.getApellido1());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_nombre_usuario = new javax.swing.JLabel();
        btn_crear_docente = new javax.swing.JButton();
        btn_crear_coordinador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_cerrar_sesion = new javax.swing.JButton();
        btn_Sedes = new javax.swing.JButton();
        btnCarrera = new javax.swing.JButton();
        btnEscuela = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido(a)");

        btn_crear_docente.setText("Gestion de Docentes");
        btn_crear_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_docenteActionPerformed(evt);
            }
        });

        btn_crear_coordinador.setText("Ingresar Coordinador");
        btn_crear_coordinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_coordinadorActionPerformed(evt);
            }
        });

        jLabel2.setText("ROL: Jefe de Carrera");

        btn_cerrar_sesion.setText("Cerrar Sesión");
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });

        btn_Sedes.setText("Sedes");
        btn_Sedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SedesActionPerformed(evt);
            }
        });

        btnCarrera.setText("Carreras");
        btnCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarreraActionPerformed(evt);
            }
        });

        btnEscuela.setText("Escuela");
        btnEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscuelaActionPerformed(evt);
            }
        });

        btn_reportes.setText("Reporte General");
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        jButton1.setText("Reporte Específico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jl_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnEscuela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cerrar_sesion)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(btn_reportes)
                    .addComponent(btn_Sedes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_crear_coordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_crear_docente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jl_nombre_usuario))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sedes)
                    .addComponent(btn_crear_docente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear_coordinador)
                    .addComponent(btnCarrera))
                .addGap(18, 18, 18)
                .addComponent(btn_reportes)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cerrar_sesion)
                    .addComponent(btnEscuela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crear_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_docenteActionPerformed
        IngresarDocente frame = new IngresarDocente();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_crear_docenteActionPerformed

    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        Inicio.usuarioActual = null;
        Inicio frame = new Inicio();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    private void btn_SedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SedesActionPerformed
       this.setVisible(false);
       Sedes sed = new Sedes();
       sed.setVisible(true);
    }//GEN-LAST:event_btn_SedesActionPerformed

    private void btn_crear_coordinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_coordinadorActionPerformed
        IngresarCoordinador frame = new IngresarCoordinador();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_crear_coordinadorActionPerformed

    private void btnCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarreraActionPerformed
        CrearCarrera ce = new CrearCarrera();
        this.setVisible(false);
        ce.setVisible(true);        
    }//GEN-LAST:event_btnCarreraActionPerformed

    private void btnEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscuelaActionPerformed
        CoordinadorCrearEscuela co= new CoordinadorCrearEscuela();
        this.setVisible(false);
        co.setVisible(true);
    }//GEN-LAST:event_btnEscuelaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ReportesJefeCarreraEspecifico frame = new ReportesJefeCarreraEspecifico();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        ReportesJefeCarrera frame = new ReportesJefeCarrera();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexJefeCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexJefeCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexJefeCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexJefeCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IndexJefeCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrera;
    private javax.swing.JButton btnEscuela;
    private javax.swing.JButton btn_Sedes;
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JButton btn_crear_coordinador;
    private javax.swing.JButton btn_crear_docente;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jl_nombre_usuario;
    // End of variables declaration//GEN-END:variables
}
